"""Application services package."""

from app.services.auth_service import (
	AuthService,
	AuthServiceError,
	EmailNotVerifiedError,
	EmailAlreadyRegisteredError,
	EmptyRegistrationInfoUpdateError,
	InactiveUserError,
	InvalidCredentialsError,
)
from app.services.ai_service import (
	AIService,
	AIServiceConfigError,
	AIServiceConnectionError,
	AIServiceError,
	AIServiceResponseError,
	AIServiceTimeoutError,
)
from app.services.profile_service import (
	EmptyProfileUpdateError,
	InvalidCurrentPasswordError,
	InvalidProfileDataError,
	ProfileNotFoundError,
	ProfileRoleRequiredError,
	ProfileService,
	ProfileServiceError,
)
from app.services.coach_client_service import (
	CoachClientNotFoundError,
	CoachClientRequestNotFoundError,
	CoachClientRelationshipExistsError,
	CoachClientRelationshipNotFoundError,
	CoachClientService,
	CoachClientServiceError,
	CoachRoleRequiredError,
	InvalidCoachClientAssignmentError,
)
from app.services.storage_service import (
	ImageTooLargeError,
	StorageConfigurationError,
	StorageService,
	StorageServiceError,
	UnsupportedImageTypeError,
)
from app.services.upload_service import (
	UploadService,
	UploadServiceError,
	UploadUserNotFoundError,
)
from app.services.routine_service import (
	EmptyRoutineUpdateError,
	RoutineClientNotFoundError,
	RoutineClientNotManagedError,
	RoutineRecentFood,
	RoutineAlreadyExistsError,
	RoutineNotFoundError,
	RoutineService,
	RoutineServiceError,
)
from app.services.nutrition_plan_service import (
	NutritionPlanAlreadyExistsError,
	NutritionPlanClientNotFoundError,
	NutritionPlanClientNotManagedError,
	NutritionPlanNotFoundError,
	NutritionPlanService,
	NutritionPlanServiceError,
)
from app.services.workout_plan_service import (
	EmptyWorkoutPlanUpdateError,
	InvalidWorkoutPlanAssignmentError,
	WorkoutPlanAssignmentExistsError,
	WorkoutPlanClientNotFoundError,
	WorkoutPlanClientNotManagedError,
	WorkoutPlanNotFoundError,
	WorkoutPlanService,
	WorkoutPlanServiceError,
)
from app.services.email_service import EmailService
from app.services.verification_service import (
	ExpiredVerificationCodeError,
	InvalidVerificationCodeError,
	VerificationService,
	VerificationServiceError,
)
from app.services.verification_flow_service import (
	VerificationFlowService,
	VerificationFlowServiceError,
	VerificationUserNotFoundError,
)

__all__ = [
	"AuthService",
	"AuthServiceError",
	"EmailNotVerifiedError",
	"EmailAlreadyRegisteredError",
	"EmptyRegistrationInfoUpdateError",
	"InactiveUserError",
	"InvalidCredentialsError",
	"AIService",
	"AIServiceConfigError",
	"AIServiceConnectionError",
	"AIServiceError",
	"AIServiceResponseError",
	"AIServiceTimeoutError",
	"EmptyProfileUpdateError",
	"InvalidCurrentPasswordError",
	"InvalidProfileDataError",
	"ProfileNotFoundError",
	"ProfileRoleRequiredError",
	"ProfileService",
	"ProfileServiceError",
	"CoachClientNotFoundError",
	"CoachClientRequestNotFoundError",
	"CoachClientRelationshipExistsError",
	"CoachClientRelationshipNotFoundError",
	"CoachClientService",
	"CoachClientServiceError",
	"CoachRoleRequiredError",
	"InvalidCoachClientAssignmentError",
	"ImageTooLargeError",
	"StorageConfigurationError",
	"StorageService",
	"StorageServiceError",
	"UnsupportedImageTypeError",
	"UploadService",
	"UploadServiceError",
	"UploadUserNotFoundError",
	"EmptyRoutineUpdateError",
	"RoutineClientNotFoundError",
	"RoutineClientNotManagedError",
	"RoutineRecentFood",
	"RoutineAlreadyExistsError",
	"RoutineNotFoundError",
	"RoutineService",
	"RoutineServiceError",
	"NutritionPlanClientNotFoundError",
	"NutritionPlanAlreadyExistsError",
	"NutritionPlanClientNotManagedError",
	"NutritionPlanNotFoundError",
	"NutritionPlanService",
	"NutritionPlanServiceError",
	"EmptyWorkoutPlanUpdateError",
	"InvalidWorkoutPlanAssignmentError",
	"WorkoutPlanAssignmentExistsError",
	"WorkoutPlanClientNotFoundError",
	"WorkoutPlanClientNotManagedError",
	"WorkoutPlanNotFoundError",
	"WorkoutPlanService",
	"WorkoutPlanServiceError",
	"EmailService",
	"ExpiredVerificationCodeError",
	"InvalidVerificationCodeError",
	"VerificationService",
	"VerificationServiceError",
	"VerificationFlowService",
	"VerificationFlowServiceError",
	"VerificationUserNotFoundError",
]